name: Push CI Image

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - docker-image-tag: "ci"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract build args
        # Extract version from branch name
        # Example: branch name `release/1.0.0` sets up env.RELEASE_VERSION=1.0.0
        run: |
          echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "BUILD_USER=$(id -u -n)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bytebase/bb:${{ matrix.docker-image-tag }}
          build-args: |
            VERSION=ci
            GIT_COMMIT=${{ env.GIT_COMMIT }}
            BUILD_TIME=${{ env.BUILD_TIME }}
            BUILD_USER=${{ env.BUILD_USER }}
      - name: Image digest
        run: echo "Successfully pushed bytebase/bb:${{ matrix.docker-image-tag }} " ${{ steps.docker_build.outputs.digest }}
